[package]
name = "uds_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder.workspace = true
thiserror.workspace = true
# Optional dependencies
clap = { workspace = true }
serde = { workspace = true }
static_assertions = "1.1.0"
