[package]
name = "uds_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
uds_protocol_derive = { path = "uds_protocol_derive" }
byteorder.workspace = true
thiserror.workspace = true
# Optional dependencies
clap = { workspace = true }
serde = { workspace = true}
serde_bytes = "0.11.15"
static_assertions = "1.1.0"
bitmask-enum = "2.2.5"
