[package]
name = "uds_protocol"
authors = ["Justin Kovacich<justin.kovacich@luminartech.com>",
"Kimberly Kryger <kim.kryger@luminartech.com>",
"Matthew Beisser <matthew.beisser@luminartech.com>",
"Parth Patel <parth.patel@luminartech.com>",
"Zachary Heylmun <zachary.heylmun@luminartech.com>", ]
version = "0.0.1"
edition = "2024"

[dependencies]
uds_protocol_derive = { path = "./uds_protocol_derive", version = "0.0.1" }
byteorder = "1"
thiserror = "2"
utoipa = "5"
# Optional dependencies
clap = { version = "4", features = ["derive"] }
serde = "1"
serde_bytes = "0.11"
static_assertions = "1"
bitmask-enum = "2"
