[package]
name = "uds_protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder.workspace = true
thiserror.workspace = true
num = "0.4.3"
# Optional dependencies
clap = { workspace = true }
serde = { workspace = true}
serde_ini = {workspace = true}
serde_yaml = {workspace = true}
static_assertions = "1.1.0"
serde_bytes = "0.11.15"
