[package]
name = "uds_protocol_derive"
version = "0.1.0"
edition = "2021"

[lib]
name = "uds_protocol_derive"
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true, features = ["proc-macro"] }
quote = "1.0"
syn = "2.0"

[features]
default = []
