[package]
name = "uds_protocol_derive"
version = "0.1.0"
edition = "2024"

[lib]
name = "uds_protocol_derive"
proc-macro = true

[dependencies]
proc-macro2 = { version="1", features = ["proc-macro"] }
quote = "1"
syn = "2"

[features]
default = []
